import Link from "next/link";

/**
 * THE TRAIL AT THE TOP OF A PAGE
 *
 * "KUL / Services / Power Only", and every step before the last one goes
 * somewhere.
 *
 * IT USED TO BE SEVEN COPIES OF THE SAME MARKUP, ALL OF THEM DEAD. Each page
 * wrote its own row of three spans, so the trail looked like a breadcrumb and
 * behaved like a caption: KUL did not go home, Services did not go to the
 * services page, and there was nothing to tell a screen reader that any of it
 * was navigation. The client asked for the links; the duplication is why they
 * were missing in the first place, so the seven copies are now this one file.
 *
 * THE LAST STEP IS NEVER A LINK. It is the page you are already on, so linking
 * it offers a reader a journey to where they are standing. It carries
 * `aria-current="page"` instead, which is what a screen reader announces, and
 * it is the one step set in gold.
 *
 * ON THE MARKUP. A `nav` with an ordered list inside it, because the order is
 * the meaning. The separators are generated by CSS rather than typed as
 * elements, so they are never read out as the word "slash" between every item.
 */

export type Crumb = {
  label: string;
  /** Omitted on the last item, which is the current page. */
  href?: string;
};

export default function Breadcrumb({
  items,
  tone = "light",
  className,
}: {
  items: readonly Crumb[];
  /** Which ground it sits on, so it picks the right greys. */
  tone?: "light" | "dark";
  className?: string;
}) {
  const muted = tone === "dark" ? "text-k-on-dark-soft" : "text-k-ink-faint";
  const current = tone === "dark" ? "text-k-gold-lit" : "text-k-gold";
  const hoverTo = tone === "dark" ? "hover:text-k-on-dark" : "hover:text-k-ink";

  return (
    <nav aria-label="Breadcrumb" className={className}>
      <ol className="flex flex-wrap items-center gap-x-2.5 gap-y-1">
        {items.map((item, i) => {
          const last = i === items.length - 1;
          return (
            <li
              key={item.label}
              // The separator belongs to the item that follows it, so the
              // first one never gets a leading slash and the row can wrap
              // without stranding one at the start of a line.
              className={`flex items-center gap-2.5 font-text text-k-micro uppercase ${
                last ? current : muted
              } ${i > 0 ? "before:content-['/'] before:text-k-ink-faint" : ""} ${
                i > 0 && tone === "dark" ? "before:text-k-on-dark-faint" : ""
              }`}
            >
              {last || !item.href ? (
                <span aria-current="page">{item.label}</span>
              ) : (
                /* 11px of caps sets a 16px line box, so the only way back up
                   the breadcrumb was a 16px-tall target. These are navigation
                   rather than links inside a sentence, so they get no help from
                   the inline exemption in WCAG 2.5.8 and were simply under the
                   24px minimum. The pseudo-element takes them to 28 without
                   moving the row; the separator lives on the `li`, so the
                   link's own `before` was free to use. */
                <Link
                  href={item.href}
                  className={`relative underline-offset-4 transition-colors duration-200 before:absolute before:-inset-y-1.5 before:inset-x-0 before:content-[''] hover:underline ${hoverTo}`}
                >
                  {item.label}
                </Link>
              )}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}
